#' @title loadGWIPSdata
#' @description Loads data from GWIPS database (in BigWig format) for forward and reverse strands into global GRanges objects. As a result, global objects "gwips_forw" and "gwips_rev" become available for further analyses.
#'
#' @param forward path to the BigWig file containing Riboseq data for forward strand
#' @param reverse path to the BigWig file containing Riboseq data for forward strand
#' @import rtracklayer
#'
#' @return list containing forward and reverse objects
#' @export loadGWIPSdata
loadGWIPSdata <- function(forward, reverse) {
  stopifnot(file.exists(forward))
  stopifnot(file.exists(reverse))
  riboseqlist <- list()
  riboseqlist["forward"] <- rtracklayer::import(con = forward, format = "bigWig")
  riboseqlist["reverse"] <- rtracklayer::import(con = reverse, format = "bigWig")
  riboseqlist
}


#' @title verifySeqLevels
#' @description Assumes that global variables gwips_forw and gwips_rev are available. This function checks if the seqLevels in all Genomic Ranges objects are the same. It's a sanity-check function, not to be used directly.
#'
#' @param riboseqlist a list containing two GR objects generated by \code{loadGWIPSdata} function
#' @param x Genomic Ranges object from the genome annotation
#' @import GenomicRanges
#'
#' @return FALSE if seqLevels are different, TRUE if everything is OK
#' @export verifySeqLevels
verifySeqLevels <- function(riboseqlist, gr) {
  if (!(exists(riboseqlist["forward"]) && exists(riboseqlist["reverse"]))) {
    stop("Wrong object, riboseqlist required.")
  }

  if (!((seqlevels(riboseqlist["forward"]) == seqlevels(riboseq["reverse"])) &&
        (seqlevels(riboseqlist["reverse"]) == seqlevels(x)))) {
    print("Please correct seqlevels in your Granges objects.")
    FALSE
  } else {
    TRUE
  }
}


#' pattern plot
#' @param data data for plot
#' @param pattern pattern (conforms to PERL style)
#'
#' @export
#' @return ggplot object
pattern_plot <- function(data, pattern){
  ggplot(data, aes(x=variable, y=riboseq, group=variable)) + geom_boxplot(notch = TRUE, outlier.shape = NA) +
    labs(title=paste("Elongating ribosome occupupancy at first 15 positions of E. coli genes for pattern", pattern)) + scale_y_log10() +
    ylab("Occupancy") + xlab("Position, from 1st to 15th") + theme_light()
}


#' get data summary
#' @param mydf data to extract
#' @param pattern pattern to choose from
#'
#' @export
dataExtract <- function(mydf, pattern){

  if (is.null(pattern)){
    pattern <- "M"
  }

  tmp.df <- mydf[[4]][which(mydf[[4]]$ID == "gene:b3652"), ]
  for (i in seq_along(mydf)) {
    tmp.df <-
      rbind(tmp.df, mydf[[i]][grep(paste0("^", pattern), mydf[[i]][36]$V36, perl = TRUE),])
  }
  data4plot <- melt(
    tmp.df,
    id.vars = c("ID"),
    measure.vars = c(
      "RS1",
      "RS2",
      "RS3",
      "RS4",
      "RS5",
      "RS6",
      "RS7",
      "RS8",
      "RS9",
      "RS10",
      "RS11",
      "RS12",
      "RS13",
      "RS14",
      "RS15"
    ),
    value.name = "riboseq"
  )
  data4plot$riboseq[which(data4plot$riboseq == 0)] <- NA
  data4plot$riboseq <- as.numeric(data4plot$riboseq)
  data4plot
}

#' data summary
#' @param data.for.plot
#'
#' @export
dataSummary <- function(data.for.plot){
  no.genes <- length(unique(data.for.plot$ID))
  no.observations <- length(data.for.plot$riboseq[!is.na(data.for.plot$riboseq)])
  list(genes = no.genes, observations = no.observations)
}
